# SPDX-FileCopyrightText: 2024 Thomas Mathys
# SPDX-License-Identifier: MIT

function(vtg_target_enable_warnings target)

  if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    # Using -Weverything is not recommended by clang developers, see
    # https://quuxplusone.github.io/blog/2018/12/06/dont-use-weverything
    # We start out with it anyway and see how it goes.
    target_compile_options(${target} INTERFACE -Werror)
    target_compile_options(${target} INTERFACE -Weverything)
    target_compile_options(${target} INTERFACE -Wno-c++20-compat)
    target_compile_options(${target} INTERFACE -Wno-c++98-compat)
    target_compile_options(${target} INTERFACE -Wno-c++98-compat-bind-to-temporary-copy)
    target_compile_options(${target} INTERFACE -Wno-c++98-compat-pedantic)
    target_compile_options(${target} INTERFACE -Wno-ctad-maybe-unsupported)
    target_compile_options(${target} INTERFACE -Wno-padded)
    target_compile_options(${target} INTERFACE -Wno-switch-default)
    target_compile_options(${target} INTERFACE -Wno-unsafe-buffer-usage)
    target_compile_options(${target} INTERFACE -Wno-weak-vtables)
  endif()

  if(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    # General warning options (https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html)
    target_compile_options(${target} INTERFACE -Werror)
    target_compile_options(${target} INTERFACE -Wall)
    target_compile_options(${target} INTERFACE -Wextra)
    target_compile_options(${target} INTERFACE -Wpedantic)
    target_compile_options(${target} INTERFACE -Walloca)
    target_compile_options(${target} INTERFACE -Walloc-zero)
    target_compile_options(${target} INTERFACE -Wcast-align=strict)
    target_compile_options(${target} INTERFACE -Wcast-qual)
    target_compile_options(${target} INTERFACE -Wdisabled-optimization)
    target_compile_options(${target} INTERFACE -Wdouble-promotion)
    target_compile_options(${target} INTERFACE -Wduplicated-branches)
    target_compile_options(${target} INTERFACE -Wduplicated-cond)
    target_compile_options(${target} INTERFACE -Wfloat-equal)
    target_compile_options(${target} INTERFACE -Wformat=2)
    target_compile_options(${target} INTERFACE -Winit-self)
    target_compile_options(${target} INTERFACE -Winvalid-pch)
    target_compile_options(${target} INTERFACE -Wlogical-op)
    target_compile_options(${target} INTERFACE -Wmissing-declarations)
    target_compile_options(${target} INTERFACE -Wmissing-include-dirs)
    target_compile_options(${target} INTERFACE -Wnull-dereference)
    target_compile_options(${target} INTERFACE -Wpointer-arith)
    target_compile_options(${target} INTERFACE -Wredundant-decls)
    target_compile_options(${target} INTERFACE -Wshift-overflow=2)
    target_compile_options(${target} INTERFACE -Wsign-conversion)
    target_compile_options(${target} INTERFACE -Wswitch-enum)
    target_compile_options(${target} INTERFACE -Wtrampolines)
    target_compile_options(${target} INTERFACE -Wundef)
    target_compile_options(${target} INTERFACE -Wvector-operation-performance)
    target_compile_options(${target} INTERFACE -Wwrite-strings)
    # C++ dialect options (https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Dialect-Options.html)
    target_compile_options(${target} INTERFACE -Wctor-dtor-privacy)
    target_compile_options(${target} INTERFACE -Wold-style-cast)
    target_compile_options(${target} INTERFACE -Woverloaded-virtual)
    target_compile_options(${target} INTERFACE -Wstrict-null-sentinel)
    target_compile_options(${target} INTERFACE -Wsuggest-final-methods)
    target_compile_options(${target} INTERFACE -Wsuggest-final-types)
    target_compile_options(${target} INTERFACE -Wsuggest-override)
    target_compile_options(${target} INTERFACE -Wunsafe-loop-optimizations)
    target_compile_options(${target} INTERFACE -Wuseless-cast)
    target_compile_options(${target} INTERFACE -Wzero-as-null-pointer-constant)
  endif()

  if(MSVC)
    target_compile_options(${target} INTERFACE /WX)
    target_compile_options(${target} INTERFACE /W4)
  endif()

endfunction()
